# -*- coding: utf-8 -*-
from iq.models import *
towns=[
['Praha','A',True],
['Brno','B',True],
['Ostrava','T',True],
['Plzeň','P',True],
['Liberec','L',True],
['Olomouc','M',True],
['Ústí nad Labem','U',True],
['Hradec Králové','H',True],
['České Budějovice','C',True],
['Pardubice','E',True],
['Havířov','T',False],
['Zlín','Z',True],
['Kladno','S',False],
['Most','U',False],
['Karviná','T',False],
['Opava','T',False],
['Frýdek-Místek','T',False],
['Karlovy Vary','K',False],
['Jihlava','J',True],
['Teplice','U',False],
['Děčín','U',False],
['Chomutov','U',False],
['Přerov','M',False],
['Jablonec nad Nisou','L',False],
['Mladá Boleslav','S',False],
['Prostějov','M',False],
['Třebíč','J',False],
['Česká Lípa','L',False],
['Třinec','T',False],
['Tábor','C',False],
['Znojmo','B',False],
['Příbram','S',False],
['Cheb','K',False],
['Orlová','T',False],
['Kolín','S',False],
['Trutnov','H',False],
['Písek','C',False],
['Kroměříž','Z',False],
['Šumperk','M',False],
['Vsetín','Z',False],
['Valašské Meziříčí','Z',False],
['Litvínov','U',False],
['Uherské Hradiště','Z',False],
['Hodonín','B',False],
['Český Těšín','T',False],
['Břeclav','B',False],
['Krnov','T',False],
['Litoměřice','U',False],
['Sokolov','K',False],
['Nový Jičín','T',False],
['Havlíčkův Brod','J',False],
['Chrudim','E',False],
['Strakonice','C',False],
['Kopřivnice','T',False],
['Klatovy','P',False],
['Žďár nad Sázavou','J',False],
['Bohumín','T',False],
['Jindřichův Hradec','C',False],
['Vyškov','B',False],
['Blansko','B',False],
['Kutná Hora','S',False],
['Náchod','H',False],
['Jirkov','U',False],
['Mělník','S',False],
['Žatec','U',False],
['Hranice (okres Přerov)','M',False],
['Beroun','S',False],
['Louny','U',False],
['Otrokovice','Z',False],
['Kralupy nad Vltavou','S',False],
['Kadaň','U',False],
['Brandýs nad Labem-Stará Boleslav','S',False],
['Ostrov','K',False],
['Svitavy','E',False],
['Bruntál','T',False],
['Uherský Brod','Z',False],
['Rožnov pod Radhoštěm','Z',False],
['Jičín','H',False],
['Rakovník','S',False],
['Neratovice','S',False],
['Benešov','S',False],
['Pelhřimov','J',False],
['Dvůr Králové nad Labem','H',False],
['Česká Třebová','E',False],
['Bílina','U',False],
['Varnsdorf','U',False],
['Slaný','S',False],
['Klášterec nad Ohří','U',False],
['Mariánské Lázně','K',False],
['Nymburk','S',False],
['Ústí nad Orlicí','E',False],
['Turnov','L',False],
['Chodov','K',False],
['Rokycany','P',False],
['Hlučín','T',False],
['Poděbrady','S',False],
['Zábřeh','M',False],
['Šternberk','M',False],
['Krupka','U',False],
['Říčany','S',False],
['Český Krumlov','C',False],
['Roudnice nad Labem','U',False],
['Aš','K',False],
['Tachov','P',False],
['Vrchlabí','H',False],
['Jaroměř','H',False],
['Vysoké Mýto','E',False],
['Nový Bor','L',False],
['Holešov','Z',False],
['Vlašim','S',False],
['Uničov','M',False],
['Jeseník','M',False],
['Velké Meziříčí','J',False],
['Čelákovice','S',False],
['Kyjov','B',False],
['Veselí nad Moravou','B',False],
['Boskovice','B',False],
['Prachatice','C',False],
['Rychnov nad Kněžnou','H',False],
['Sušice','P',False],
['Rumburk','U',False],
['Domažlice','P',False],
['Frenštát pod Radhoštěm','T',False],
['Humpolec','J',False],
['Kuřim','B',False],
['Moravská Třebová','E',False],
['Nové Město na Moravě','J',False],
['Litomyšl','E',False],
['Lanškroun','E',False],
['Čáslav','S',False],
['Hlinsko','P',False],
['Studénka','T',False]
]

schemes = [['školní'],['neškolní']]

levels = [
    ['zš',1,1],['sš',2,1],['vš',3,1],
    ['začátečník',1,2],['pokročilý',2,2],['expert',3,2]
]

categories = [
    ['Přírodní vědy','Přírodní vědy je označení pro soubor věd zkoumajících vědeckými metodami řád a zákony, kterými se řídí vesmír, vycházející z přírodní filosofie. Důsledným užíváním čistě vědeckých metod se odlišují od filosofie, teologie a společenských věd a jsou základem pro rozvíjení tzv. aplikovaných věd.'],
    ['Humanitní vědy','Humanitní vědy či také duchovní vědy (z něm. Geisteswissenschaft) jsou vědy pojednávající o některé skupině produktů duchovních procesů, např. o filozofii, etice, umění, jazycích, náboženství apod. Pojem „duchovní věda“ pochází z němčiny a tam zas původně z anglického „Moral sciences“. V anglickém kulturním okruhu mu přibližně odpovídá pojem „humanitní“ (humanistiky) nebo „social sciences“ (společenské vědy), ve francouzském „Lettres“ nebo „sciences humaines“ (humánní vědy).'],
    ['Informační technologie','Informační technologie je odvětví techniky, které se zabývá tvorbou, zaváděním a zdokonalováním procesů a metod sběru (shromažďování), kontroly, zpracování, uchování, vyhledávání, řízení, výměny, zobrazování, zpřístupňování a využívání dat a informací, zahrnující automatizaci těchto procesů.'],
]

subjects = [
    ['Chemie','Chemie je věda, která se zabývá vlastnostmi, složením, přípravou, strukturou anorganických a organických látek a jejich vzájemnými interakcemi. Látky jsou složeny z atomů a z nich složených molekul nebo z iontů.',1,1],
    ['Programování','Programování je v informatice proces od návrhu řešení problému pomocí výpočetní techniky ke spustitelnému počítačovému programu. Zahrnuje činnosti jako je analýza problému, jeho pochopení, nalezení algoritmu a zápis zdrojového kódu v cílovém programovacím jazyce (kódování, anglicky coding).',3,2],
]

def init():
    Settings().save()
    for t in towns:
        Town(name=t[0],county=t[1],countyCapital=t[2]).save()
    for s in schemes:
        Scheme(name=s[0]).save()
    for l in levels:
        Level(name=l[0],order=l[1],scheme=Scheme.objects.get(pk=l[2])).save()
    for c in categories:
        Category(name=c[0],description=c[1]).save()
    for s in subjects:
        Subject(name=s[0],description=s[1],category=Category.objects.get(pk=s[2]),scheme=Scheme.objects.get(pk=s[3])).save()
